# Generated by Django 3.2.8 on 2022-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptp', '0002_persona_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.CharField(max_length=50),
        ),
    ]
