# Generated by Django 3.2.8 on 2022-04-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptp', '0003_auto_20220331_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
